### PR TITLE
Big but needed changes

### PR DESCRIPTION
**Pull request by guilhem**
Please upload this version to the "community" website.

Previous one doen't work.

### CODE REVIEW

**Comment by cwjohnston** [comment]
I'm happy to merge this but I don't control the listing on the community site for vsftpd. Try @rberger.

**Comment by rberger** [comment]
Hey, I'm @rberger but not clear what is needed. Be glad to help out.

**Comment by guilhem** [comment]
Hi,
it's needed because (in my case) the current master branch doesn't work. I know, I may open an issue for this (and I don't remember what was the problem), but this version fix the problem and add many features / documentation... what else? :)

**Comment by rberger** [comment]
I made Cameron  a Collaborator (and would be glad to "promote" him to maintainer) on the Opscode Community Cookbook site for the vsftpd cookbook. Cameron, if for some reason you don't want that awesome responsibility and power, let me know what I should merge and push to opscode.

**Pull request merged**
